name: Publish to npm

on:
  workflow_call:
    inputs:
      paths:
        description: 'The paths that were released as JSON array string. E.g. ["packages/namespace"]'
        required: true
        type: string

permissions:
  contents: read
  id-token: write # Required for npm provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish with provenance
        run: npm publish --workspace=${{ join(fromJson(inputs.paths), ' --workspace=') }} --provenance --access public
